calendar is ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #10
Opened 2023-03-16 11:10 UTC by KiraIsmailova

создан календарь

2023-03-16 11:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 11:20 UTC, GSemikozov requested changes

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    display: inline-grid;
вот здесь задаем общие паддинги

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 28px;
лишнее, см ниже

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    text-align: right;
вроде по центру, не по правому краю надо

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-columns: repeat(7, 30px);
30px -> 1fr

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__number div:first-child {
вместо div - класс

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <h1 class="calendar__title">October 2019</h1>
h3-h5

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__days {
это часть общего грида calendar__number (переименуем в calendar__numbers?)

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__days {
а если стили немного отличаются - то модификатор calendar__numbers_week-day

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div>1</div>
элемент calendar__day

2023-03-16 11:20 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__blue">18</div>
calendar__day, а фон меняем через модификатор, например calendar__day_start / calendar__day_end / calendar__day_between

2023-03-16 11:20 UTC, GSemikozov commented on assets/css/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;400&family=Roboto:wght@500&family=Source+Sans+Pro:ital@0;1&display=swap');
подключаем в fonts.css

2023-03-16 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 19:44 UTC, KiraIsmailova commented on assets/css/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;400&family=Roboto:wght@500&family=Source+Sans+Pro:ital@0;1&display=swap');
переподключила

2023-03-16 19:44 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <h1 class="calendar__title">October 2019</h1>
сделано

2023-03-16 19:45 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-columns: repeat(7, 30px);
вместо 30px теперь 1f

2023-03-16 19:45 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +    text-align: right;
исправлено на центр

2023-03-16 19:45 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 28px;
убрала

2023-03-16 19:45 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +    display: inline-grid;
+

2023-03-16 20:09 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__blue">18</div>
исправлены имена классов

2023-03-16 20:09 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <div>1</div>
исправлено

2023-03-16 20:10 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +.calendar__days {
готово

2023-03-16 21:25 UTC, GSemikozov requested changes

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +        <main class="calendar">
поскольку блок будем переиспользовать, то здесь - `<div>`

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__day_week-day">1</div>
модификаторы сами по себе использовать нельзя, обязательно с тем, ЧТО они модифицирую, то есть - `<div class="calendar__day calendar__day_week-day">`

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div>2</div>
у всех div то же самое - `<div class="calendar__day">`

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__day_week-day">1</div>
только calendar__day_week-day я предлагал использовать для div внутри calendar__numbers, если имена дней недели делать в общег гриде внутри поскольку calendar__days )

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__day_start">18</div>
а здесь `<div class="calendar__day calendar__day_start">18</div>` и тд

2023-03-16 21:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 24px;
`28px 26px 32px`

2023-03-17 08:56 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +        <main class="calendar">
готово

2023-03-17 09:03 UTC, KiraIsmailova commented on 05-lection3/03-calendar/calendar.css
> +    padding: 24px;
паддинги исправлены

2023-03-17 09:03 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__day_start">18</div>
готово

2023-03-17 09:03 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <div>2</div>
готово, всем div задала class="calendar__day"

2023-03-17 09:05 UTC, KiraIsmailova commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__day_week-day">1</div>
первое замечание исправлено. второе - решила поменять название модификатора на calendar__day_first-day, чтобы не было неточностей

2023-03-17 15:38 UTC, GSemikozov approved these changes

2023-03-17 15:38 UTC, merged