Tooltip
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #11
Opened 2023-03-16 19:18 UTC by KiraIsmailova

сделан тултип

2023-03-16 19:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 19:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 20:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 21:26 UTC, GSemikozov requested changes

2023-03-16 21:26 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 100px;
марджины на уровне блока не задаем

2023-03-17 09:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 09:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-17 15:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-17 15:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-17 15:59 UTC, GSemikozov approved these changes

2023-03-17 15:59 UTC, merged