Modal
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #12
Opened 2023-03-20 15:23 UTC by KiraIsmailova

модальное окно готово

2023-03-20 15:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 10:42 UTC, GSemikozov requested changes

2023-03-22 10:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.wrapper {
все-таки блок не wrapper а modal ;)

2023-03-22 10:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.wrapper {
сам блок растягиваем на 100vw + 100vh и позиционируем через fixed. По умолчанию - display: none

2023-03-22 10:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--grey-5);
и фон делаем полупрозрачным через rgba

2023-03-22 10:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    .wrapper__container {
здесь не хватает радиусов и координаты должны ставить блок по середине родителя

2023-03-22 10:42 UTC, GSemikozov commented on components/button/button.css
> +.button {
у нас уже есть кнопка, стили подключены в main.css

2023-03-22 14:05 UTC, KiraIsmailova commented on 05-lection3/02-modal/modal.css
> +.wrapper {
блоки переименованы. а с остальным возникли проблемы. окно уехало и его почти не видно

2023-03-22 14:05 UTC, KiraIsmailova commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--grey-5);
фон исправлен на rgba

2023-03-22 14:06 UTC, KiraIsmailova commented on 05-lection3/02-modal/modal.css
> +    .wrapper__container {
радиусы добавлены

про координаты непонятно(((

2023-03-22 14:08 UTC, KiraIsmailova commented on components/button/button.css
> +.button {
этот момент не поняла. действительно, кнопка подключена через main.css

2023-03-22 20:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    .wrapper__container {
уже традиционный паттерн размещения элемента по середине через абсолют: `top: 50%; left: 50%; transform: translate(-50%, -50%)`

2023-03-22 20:31 UTC, GSemikozov requested changes

2023-03-22 20:31 UTC, GSemikozov commented on components/button/button.css
> +.button {
а зачем тогда нам еще кнопка в `components/button/button.css`?

2023-03-22 20:59 UTC, KiraIsmailova commented on components/button/button.css
> +.button {
я удалила сейчас эту папку с файлом, теперь кнопка у меня стала без оформлений вообще

2023-03-22 20:59 UTC, KiraIsmailova commented on 05-lection3/02-modal/modal.css
> +    .wrapper__container {
поняла. но все равно получился ужас

2023-03-22 21:00 UTC, KiraIsmailova commented on components/button/button.css
> +.button {
кнопка была сделана в ветке button у меня, и когда я в другой ветке, то этого не видно

2023-03-22 21:26 UTC, KiraIsmailova commented on 05-lection3/02-modal/modal.css
> +    .wrapper__container {
окно моталки огромное, на всю страницу

2023-03-24 07:47 UTC, GSemikozov requested changes

2023-03-24 07:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    .modal__container {
чтобы окно не было огромным, можно ограничить через max-width как на макете

2023-03-28 16:08 UTC, GSemikozov approved these changes

2023-03-28 16:08 UTC, merged