avatar is ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #13
Opened 2023-03-21 22:22 UTC by KiraIsmailova

создан аватар

2023-03-21 22:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 10:43 UTC, GSemikozov requested changes

2023-03-22 10:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    box-shadow: 0px 2px 4px rgba(33, 36, 41, 0.05);
тень и радиус удалим, а вот размеры - зафиксируем (квадрат)

2023-03-22 10:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
лишнее

2023-03-22 10:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__title {
удалим

2023-03-22 10:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__image {
height должна быть тоже 100%

2023-03-22 10:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__image {
и border-radius: 50%

2023-03-22 13:54 UTC, KiraIsmailova commented on 06-lection4/01-avatar/avatar.css
> +.avatar__title {
готово

2023-03-22 13:54 UTC, KiraIsmailova commented on 06-lection4/01-avatar/avatar.css
> +.avatar__image {
исправлено

2023-03-22 13:57 UTC, KiraIsmailova commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
убрала

2023-03-22 13:57 UTC, KiraIsmailova commented on 06-lection4/01-avatar/avatar.css
> +    box-shadow: 0px 2px 4px rgba(33, 36, 41, 0.05);
тень и радиус удалены, размеры зафиксировали

2023-03-22 13:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 14:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-22 20:29 UTC, GSemikozov requested changes

2023-03-22 20:29 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
неа, все еще здесь)

2023-03-22 20:29 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__title {
неа)

2023-03-22 20:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 21:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-24 20:05 UTC, GSemikozov requested changes

2023-03-24 20:05 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
удалим

2023-03-24 20:05 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__title {
удалим

2023-03-24 20:05 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +        <div class="avatar">
оставляем только avatar + avatar__img

2023-03-24 20:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 20:06 UTC, GSemikozov requested changes

2023-03-24 20:06 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +                <a href="path/to/image.jpg" download>
и тег а удалим

2023-03-24 20:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 20:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-25 13:52 UTC, GSemikozov approved these changes

2023-03-25 13:53 UTC, merged