toggler ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #20
Opened 2023-03-30 13:29 UTC by KiraIsmailova

готовы кнопки переключатели

2023-03-30 13:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-31 16:39 UTC, GSemikozov requested changes

2023-03-31 16:39 UTC, GSemikozov commented on 07-lection5/03-toggler/index.html
> +            Off
текст все равно лучше обернуть в какой-то тег

2023-03-31 16:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    font-family: 'Inter';
текстовые свойства советовал бы перенести для элемента текста

2023-03-31 16:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +	height: 28px;
высоту - на .toggler__state

2023-03-31 17:10 UTC, KiraIsmailova commented on 07-lection5/03-toggler/index.html
> +            Off
обернула

2023-03-31 17:11 UTC, KiraIsmailova commented on 07-lection5/03-toggler/toggler.css
> +    font-family: 'Inter';
готово

2023-03-31 17:12 UTC, KiraIsmailova commented on 07-lection5/03-toggler/toggler.css
> +	height: 28px;
готово

2023-03-31 17:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-31 20:45 UTC, GSemikozov requested changes

2023-03-31 20:45 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler .toggler__state:before {
просто .toggler__state:before

2023-03-31 20:45 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler .toggler__input:checked + .toggler__state:before {
.toggler__input:checked + .toggler__state:before

2023-03-31 20:51 UTC, KiraIsmailova commented on 07-lection5/03-toggler/toggler.css
> +.toggler .toggler__state:before {
исправлено)

2023-03-31 20:52 UTC, KiraIsmailova commented on 07-lection5/03-toggler/toggler.css
> +.toggler .toggler__input:checked + .toggler__state:before {
исправлено)

2023-04-04 20:12 UTC, GSemikozov approved these changes

2023-04-04 20:12 UTC, merged