ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #24
Opened 2023-04-21 21:07 UTC by KiraIsmailova

компоненты переиспользованы

2023-04-21 21:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-22 08:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 12:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 13:03 UTC, GSemikozov requested changes

2023-04-25 13:03 UTC, GSemikozov commented on components/main-template/main-template.css
> +.main_template {
.main-template (.main_template - выглядит как модификатор)

2023-04-25 13:03 UTC, GSemikozov commented on components/main-template/main-template.css
> +    height: 746px;
это лишнее, высота пусть определяется контентом внутри

2023-04-25 13:03 UTC, GSemikozov commented on components/main-template/main-template.css
> +    grid-area: article;
см выше

2023-04-25 13:03 UTC, GSemikozov commented on components/header-template/header-template.css
> +.header {
нет, хедер у нас уже есть) в `components/header`. Единственное - для прозрачного / серого фона нужен модификатор по типу .header_transparent. То же самое и для футера.

2023-04-25 13:03 UTC, GSemikozov commented on components/footer-template/footer-template.css
> +    .footer_template {
см коммент по хедеру ниже

2023-04-25 13:03 UTC, GSemikozov commented on pages/template.html
> +  <body class="body">
.page?

2023-04-25 13:03 UTC, GSemikozov commented on components/ads-template/ads-template.css
> +    grid-area: ads;
заранее блок не может знать о своем контексте использования, поэтому здесь - и ниже аналогично для других блоков - grid-area указывать не нужно. Это можно реализовать на уровне того блока, куда встраиваем данный - .page, .page__siteAds, .page__footer и тд

2023-04-25 13:03 UTC, GSemikozov commented on components/body-template/body-template.css
> +.body {
у нас для этих целей уже есть page, просто там другой темплейт, поэтому добавляем модификатор .page_inner и уже там все вот это вот)

2023-04-25 13:03 UTC, GSemikozov commented on components/nav-template/nav-template.css
> +    grid-area: nav;
см выше

2023-04-25 13:03 UTC, GSemikozov commented on pages/template.html
> +      <h4 class="burger__title burger__title_list">Components</h4>
это элементы nav или burger? не вижу где определен класс блока burger

2023-04-25 13:32 UTC, KiraIsmailova commented on components/main-template/main-template.css
> +.main_template {
поправила

2023-04-25 13:33 UTC, KiraIsmailova commented on components/main-template/main-template.css
> +    height: 746px;
убрала)

2023-04-25 13:35 UTC, KiraIsmailova commented on pages/template.html
> +  <body class="body">
исправила

2023-04-25 13:37 UTC, KiraIsmailova commented on components/body-template/body-template.css
> +.body {
готово

2023-04-25 15:20 UTC, KiraIsmailova commented on components/ads-template/ads-template.css
> +    grid-area: ads;
сделала, надеюсь, что правильно поняла

2023-04-25 15:20 UTC, KiraIsmailova commented on components/footer-template/footer-template.css
> +    .footer_template {
сделала хедер и футер

2023-04-25 15:21 UTC, KiraIsmailova commented on components/header-template/header-template.css
> +.header {
почти исправила. но в том хедере у меня почему-то не были заданы нужные свойства, и когда я убираю высоту, хедер исчезает

2023-04-25 15:25 UTC, KiraIsmailova commented on components/main-template/main-template.css
> +    grid-area: article;
убрала grid-area

2023-04-25 15:25 UTC, KiraIsmailova commented on components/nav-template/nav-template.css
> +    grid-area: nav;
grid-area убрала

2023-04-25 15:26 UTC, KiraIsmailova commented on pages/template.html
> +      <h4 class="burger__title burger__title_list">Components</h4>
сделала

2023-04-25 15:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-26 11:18 UTC, GSemikozov requested changes

2023-04-26 11:18 UTC, GSemikozov commented on components/footer-template/footer-template.css
> +    .footer_template {
если такого элемента с uppercase еще нет в футере, значит его просто надо добавить. А создавать отдельный блок для этого - точно не надо)

2023-04-26 11:18 UTC, GSemikozov commented on components/header-template/header-template.css
> +.header {
а внутри хедера на странице темплейта есть контент (заголовок и тд)? если нет - тогда в этом и причина

2023-04-26 11:18 UTC, GSemikozov commented on components/nav-template/nav-template.css
> +.burger {
все подвязывать под template не надо, просто блок nav как вариант. И - не бургер)

2023-04-26 11:18 UTC, GSemikozov commented on components/page-template/page-template.css
> +.page_inner {
этот модификатор и элементы ниже - составные части блока page, не page-template

2023-04-26 11:18 UTC, GSemikozov commented on pages/template.html
> +      <h4 class="burger__title burger__title_list">Components</h4>
лучше бергер переименовать в nav - бургер это про другое

2023-04-26 12:19 UTC, KiraIsmailova commented on components/header-template/header-template.css
> +.header {
внутри этого хедера нет, в итоговом проекте там находится кнопочка для смены темы на сайте и иконка. получается пока можно дать хедеру исчезнуть?

2023-04-26 12:43 UTC, KiraIsmailova commented on components/footer-template/footer-template.css
> +    .footer_template {
сделала

2023-04-26 12:58 UTC, KiraIsmailova commented on pages/template.html
> +      <h4 class="burger__title burger__title_list">Components</h4>
готово. да, я там переиспользовала не именно блок бургера, а только текстовую часть, оформление списка

2023-04-26 13:26 UTC, KiraIsmailova commented on components/page-template/page-template.css
> +.page_inner {
ага, вроде поняла, поправила

2023-04-26 13:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-26 13:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-26 13:28 UTC, KiraIsmailova commented on components/header-template/header-template.css
> +.header {
пока спрятала его, когда добавлю элементы, хедер появится

2023-04-26 13:38 UTC, GSemikozov requested changes

2023-04-26 13:38 UTC, GSemikozov commented on components/header-template/header-template.css
> +.header {
получается что так. Но вообще - у хедера должны быть паддинги сверху и снизу, и как минимум за счет этого у хедера будет какая-то высота)

2023-04-26 13:38 UTC, GSemikozov commented on components/page-template/page-template.css
> +.page_inner {
только отсюда все стили надо перенести в `page.css` а `page-template.css` удалить ;)

2023-04-26 13:38 UTC, GSemikozov commented on components/nav-template/nav-template.css
> +.nav {
файл переименуем в `nav.css`

2023-04-26 13:38 UTC, GSemikozov commented on components/main-template/main-template.css
> +.page__main {
если это элемент блока page - то унесем стили туда а этот файл удалим

2023-04-26 13:38 UTC, GSemikozov commented on components/header-template/header-template.css
> +.header {
а этот файл можно будет удалить

2023-04-26 13:38 UTC, GSemikozov commented on components/footer-template/footer-template.css
> +    .footer__text {
это элемент блока footer который описан в .footer.css - этот файл нам не нужен)

2023-04-26 13:38 UTC, GSemikozov commented on components/footer-template/footer-template.css
> +    .page__footer {
элемент блока page?

2023-04-26 16:18 UTC, KiraIsmailova commented on components/header-template/header-template.css
> +.header {
удалила

2023-04-26 16:24 UTC, KiraIsmailova commented on components/page-template/page-template.css
> +.page_inner {
готово

2023-04-26 16:28 UTC, KiraIsmailova commented on components/footer-template/footer-template.css
> +    .footer__text {
удалила

2023-04-26 16:29 UTC, KiraIsmailova commented on components/main-template/main-template.css
> +.page__main {
готово

2023-04-26 16:29 UTC, KiraIsmailova commented on components/footer-template/footer-template.css
> +    .page__footer {
получается, да. свойства перенесла в page.css

2023-04-26 16:30 UTC, KiraIsmailova commented on components/nav-template/nav-template.css
> +.nav {
переименовала

2023-04-26 16:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 17:09 UTC, GSemikozov approved these changes

2023-04-28 17:10 UTC, merged