ready main page
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #4
Opened 2023-03-06 16:14 UTC by KiraIsmailova

сделана общая верстка основной страницы

2023-03-06 16:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-06 18:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-06 19:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-06 20:22 UTC, GSemikozov requested changes

2023-03-06 20:22 UTC, GSemikozov commented on style.css
> +    left: 0px;
left + top удалим

2023-03-06 20:22 UTC, GSemikozov commented on style.css
> +.header__title {
все блоки надо раскидать по папкам как на занятии

2023-03-07 19:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-07 19:34 UTC, KiraIsmailova commented on style.css
> +    left: 0px;
left + top удалены

2023-03-07 19:35 UTC, KiraIsmailova commented on style.css
> +.header__title {
блоки вынесены в отдельные папки

2023-03-09 12:59 UTC, GSemikozov approved these changes

2023-03-09 12:59 UTC, merged