button is ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #5
Opened 2023-03-10 11:05 UTC by KiraIsmailova

кнопка готова. решила попробовать сделать свой файл с normalize css

2023-03-10 11:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-10 15:07 UTC, GSemikozov requested changes

2023-03-10 15:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    max-height: 48px;
просто height

2023-03-10 15:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background: #4263EB;
цвета договорились брать из переменных

2023-03-10 15:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-shadow: 6px 3px 3px gray;
лишнее, пусть просто совпадает с :hover

2023-03-10 18:01 UTC, KiraIsmailova commented on 03-lection1/01-button/button.css
> +    max-height: 48px;
max-height исправлен на просто height

2023-03-10 18:01 UTC, KiraIsmailova commented on 03-lection1/01-button/button.css
> +    background: #4263EB;
поменяла на цвета из переменных

2023-03-10 18:01 UTC, KiraIsmailova commented on 03-lection1/01-button/button.css
> +    box-shadow: 6px 3px 3px gray;
теперь active совпадает с over

2023-03-15 00:45 UTC, GSemikozov approved these changes

2023-03-15 00:45 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-15 00:47 UTC, GSemikozov approved these changes

2023-03-15 00:47 UTC, merged