histogram is ready
js-tasks-ru/htmlcss-20230227_kira-ismailova pull request #7
Opened 2023-03-12 13:07 UTC by KiraIsmailova

гистограмма готова

2023-03-15 00:48 UTC, GSemikozov requested changes

2023-03-15 00:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
лишнее ограничение

2023-03-15 00:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 21px;
вроде достаточно 3px)

2023-03-15 00:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
лишнее

2023-03-15 07:33 UTC, KiraIsmailova commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 21px;
исправлено

2023-03-15 07:33 UTC, KiraIsmailova commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
исправлено

2023-03-16 11:16 UTC, GSemikozov requested changes

2023-03-16 11:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
все еще актуально)

2023-03-16 11:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
неа, все еще болтается)

2023-03-16 19:25 UTC, KiraIsmailova commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 354px;
видимо, пропустила в тот раз. убрала

2023-03-16 19:27 UTC, KiraIsmailova commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
justify-content: center - убрала, сначала не так поняла

2023-03-16 21:20 UTC, GSemikozov approved these changes

2023-03-16 21:20 UTC, merged